// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Link: typeof import('./components/Utils/Link.vue')['default']
    MainSidebar: typeof import('./components/Sidebar/MainSidebar.vue')['default']
    Nav: typeof import('./components/header/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Title: typeof import('./components/Utils/Title.vue')['default']
    VWrapper: typeof import('./components/Virtual/VWrapper.vue')['default']
  }
}

export {}
